### ISSUE TITLE
Class 'Twig\Loader\ChainLoader' not found

### ISSUE THREAD

**Issue by hlarocque** [phproberto/joomla-twig#56] opened 2018-05-29 17:16 UTC
Hi! I've just installed the latest package of the plugin in Joomla. I followed the instruction for testing but I received this error message:
Class 'Twig\Loader\ChainLoader' not found
I've checked in all files and i cannot find any class named ChainLoader. Could a file could be missing in the package ?
Thank you!

**Comment by phproberto** [comment] 2018-05-29 17:36
Hi @hlarocque,

I've just downloaded and installed the latest version from the releases section (v1.0.3 now): 

https://github.com/phproberto/joomla-twig/releases/download/v1.0.3/joomla-twig-v1.0.3.zip

I installed it without issues in Joomla and confirmed that it works without issues.

Once installed you can confirm it works rendering the examples layout with:


```php
// Load the library so you can start using it
JLoader::import('twig.library');

// Render a layout. In this case direclty from the twig library
echo Twig::render('@library/twig/examples.html.twig');
```

If `ChainLoader` class is not found it means that you haven't the required composer dependencies installed. Maybe you didn't install the correct file? You have to use the ZIP provided in each release which includes the library and its dependencies:

![installable-joomla-twig](https://user-images.githubusercontent.com/1119272/40675262-89b65c44-6377-11e8-868c-2bb5e47fd028.png)

**Comment by hlarocque** [comment] 2018-05-29 20:32
I think I have the right file (please see attached). I’ve also checked in the dev branch of github and it was not there either.

 

Do I have to install some other package to make it work ? Actually the TWIG files are used for Mijoshop only. Maybe the package should be moved elsewhere?

 

 

HÉLÈNE LAROCQUE

PROGEXIA SOLUTIONS WEB

1446, Clémenceau
Verdun, Québec  H4H 2R1
C  438 502-6341 

 <https://www.progexia.com/> www.progexia.com
Skype ID : helene.larocque 

  _____  

Pensez environnement - N'imprimez que si nécessaire
Think Environment - Only print if necessary

 

De : Roberto Segura [mailto:notifications@github.com] 
Envoyé : 29 mai 2018 13:37
À : phproberto/joomla-twig <joomla-twig@noreply.github.com>
Cc : hlarocque <helene@progexia.com>; Mention <mention@noreply.github.com>
Objet : Re: [phproberto/joomla-twig] Class 'Twig\Loader\ChainLoader' not found (#56)

 

Hi @hlarocque <https://github.com/hlarocque> ,

I've just downloaded and installed the latest version from the releases section (v1.0.3 now):

https://github.com/phproberto/joomla-twig/releases/download/v1.0.3/joomla-twig-v1.0.3.zip

I installed it without issues in Joomla and confirmed that it works without issues.

Once installed you can confirm it works rendering the examples layout with:

// Load the library so you can start using it
JLoader::import('twig.library');
 
// Render a layout. In this case direclty from the twig library
echo Twig::render('@library/twig/examples.html.twig');

If ChainLoader class is not found it means that you haven't the required composer dependencies installed. Maybe you didn't install the correct file? You have to use the ZIP provided in each release which includes the library and its dependencies:

 <https://user-images.githubusercontent.com/1119272/40675262-89b65c44-6377-11e8-868c-2bb5e47fd028.png>

**Comment by phproberto** [comment] 2018-05-30 05:58
If you attached a file through email it didn't work.

You don't find dependencies in this repository because they are not tracked by git. They are only included in the installable zip. This is why not using the right zip can cause that issue. 

If you unzip the installable zip you should find something like this in the library vendor folder (`/extensions/libraries/twig/vendor`):

![twig-vendor](https://user-images.githubusercontent.com/1119272/40701672-20c32e0c-63df-11e8-9fe2-802ae8390769.jpg)

If you don't have a vendor folder or its content it's missing then it's not the correct file.

**Comment by hlarocque** [comment] 2018-05-30 12:45
Good morning. The name of the zip file is joomla-twig-v1.0.3 and it includes the folder you mentioned below. I took it from this page  <https://phproberto.github.io/joomla-twig/> https://phproberto.github.io/joomla-twig/ (top right).

 

I’ve also checked if everything was copied correctly during installation and it is. I can provide access to the website if you want. Just let me know.

 

 

HÉLÈNE LAROCQUE

PROGEXIA SOLUTIONS WEB

1446, Clémenceau
Verdun, Québec  H4H 2R1
C  438 502-6341 

 <https://www.progexia.com/> www.progexia.com
Skype ID : helene.larocque 

  _____  

Pensez environnement - N'imprimez que si nécessaire
Think Environment - Only print if necessary

 

De : Roberto Segura [mailto:notifications@github.com] 
Envoyé : 30 mai 2018 01:58
À : phproberto/joomla-twig <joomla-twig@noreply.github.com>
Cc : hlarocque <helene@progexia.com>; Mention <mention@noreply.github.com>
Objet : Re: [phproberto/joomla-twig] Class 'Twig\Loader\ChainLoader' not found (#56)

 

If you attached a file through email it didn't work.

You don't find dependencies in this repository because they are not tracked by git. They are only included in the installable zip. This is why not using the right zip can cause that issue.

If you unzip the installable zip you should find something like this in the library vendor folder (/extensions/libraries/twig/vendor):

 <https://user-images.githubusercontent.com/1119272/40701672-20c32e0c-63df-11e8-9fe2-802ae8390769.jpg> 

If you don't have a vendor folder or its content it's missing then it's not the correct file.

**Comment by hlarocque** [comment] 2018-05-31 13:07
Good morning. Sorry to get back to you but I need this to work quickly. Did you received my answer yesterday ? Do you want to have access to FTP or else ?

 

 

HÉLÈNE LAROCQUE

PROGEXIA SOLUTIONS WEB

1446, Clémenceau
Verdun, Québec  H4H 2R1
C  438 502-6341 

 <https://www.progexia.com/> www.progexia.com
Skype ID : helene.larocque 

  _____  

Pensez environnement - N'imprimez que si nécessaire
Think Environment - Only print if necessary

 

De : Roberto Segura [mailto:notifications@github.com] 
Envoyé : 29 mai 2018 13:37
À : phproberto/joomla-twig <joomla-twig@noreply.github.com>
Cc : hlarocque <helene@progexia.com>; Mention <mention@noreply.github.com>
Objet : Re: [phproberto/joomla-twig] Class 'Twig\Loader\ChainLoader' not found (#56)

 

Hi @hlarocque <https://github.com/hlarocque> ,

I've just downloaded and installed the latest version from the releases section (v1.0.3 now):

https://github.com/phproberto/joomla-twig/releases/download/v1.0.3/joomla-twig-v1.0.3.zip

I installed it without issues in Joomla and confirmed that it works without issues.

Once installed you can confirm it works rendering the examples layout with:

// Load the library so you can start using it
JLoader::import('twig.library');
 
// Render a layout. In this case direclty from the twig library
echo Twig::render('@library/twig/examples.html.twig');

If ChainLoader class is not found it means that you haven't the required composer dependencies installed. Maybe you didn't install the correct file? You have to use the ZIP provided in each release which includes the library and its dependencies:

 <https://user-images.githubusercontent.com/1119272/40675262-89b65c44-6377-11e8-868c-2bb5e47fd028.png>

**Comment by phproberto** [comment] 2018-05-31 13:11
Hey @hlarocque,

yes please send that info to: 

me (at) phproberto (dot) com

**Comment by phproberto** [comment] 2018-06-01 06:36
Closing this because the issue was that Mijoshop loads its own Twig version which cannot access joomla-twig vars/functions.

Thanks @hlarocque for your feedback and for testing joomla-twig.

**Closed as completed by phproberto** 2018-06-01 06:36 UTC
